feat/sponsor - add sponsor page translation
monterail/vue3-docs-pl pull request #66
Opened 2024-07-02 18:55 UTC by MateuszMichalowski

Add translation to `sponsor` page.

2024-07-02 20:17 UTC, WawrzenskiPatryk requested changes
First review in the repo, so please keep in mind I didn't fully get to know all the rules yet. All of the points raised are just to re-think the translation, as except the first one they are not really mistakes 😄

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +## Sponsorowanie Vue jako Osoba Prywatna {#sponsoring-vue-as-an-individual}
`osoba prywatna`

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +## Korzyści wynikające z Poziomów Sponsoringu {#tier-benefits}
There I wouldn't be sure about lowercasing it, since we can assume `Poziomy Sponsoringu` to be some kind of proper name (polish _nazwa własna_)

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +  - Nazwa wymieniona w pliku `BACKERS.md` dla `vuejs/core` i `vuejs/vue`.
There is an inconsistency in tier translation. `Platinum` should be `Platynowy`/`Platyna`, if we do translate all of the other tier names. Nevertheless I would consider if we should translate them, since it is common to use such tier vocabulary also in polish language, maybe except the last two.

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +- **Specjalne Globalne**:
`Globalny Sponsor Specjalny` sounds better and it makes sense, since it is limited to one sponsor only. It is also used below for `Special Global Sponsor`

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +### Platyna {#platinum}
Here tier translations are consistent :)

2024-07-02 20:17 UTC, WawrzenskiPatryk commented on src/sponsor/index.md
> +### Globalny Sponsor Specjalny {#special-global-sponsor}
This one is ok - here I would not change capitalisation since this looks again like _nazwa własna_ for a certain Sponsor

2024-07-03 08:42 UTC, MateuszMichalowski commented on src/sponsor/index.md
> +## Korzyści wynikające z Poziomów Sponsoringu {#tier-benefits}
Rather, it is a common phraseological compound so it should follow default rules like the earlier ones you've mentioned I think.

2024-07-03 08:43 UTC, MateuszMichalowski commented on src/sponsor/index.md
> +## Jak Sponsorować {#how-to-sponsor}
Yeah now when you've mentioned it does make sense to stick more with PL rules. I'll update it.

2024-07-03 08:48 UTC, MateuszMichalowski commented on src/sponsor/index.md
> +### Globalny Sponsor Specjalny {#special-global-sponsor}
But then it's own name of the tier right?

2024-07-03 08:50 UTC, MateuszMichalowski commented on src/sponsor/index.md
> +  - Nazwa wymieniona w pliku `BACKERS.md` dla `vuejs/core` i `vuejs/vue`.
Translation of last two only seams more inconsistent tbh. I would then go all or nothing. I'll stay with all mostly due last two of them.

2024-07-03 09:10 UTC, WawrzenskiPatryk approved these changes
LGTM :)

2024-07-04 08:04 UTC, szymonlicau requested changes

2024-07-04 08:04 UTC, szymonlicau commented on src/sponsor/index.md
> +Możesz również spróbować przekonać swojego pracodawcę do sponsorowania Vue jako firmy. Może to nie być łatwe, ale sponsoring biznesowy zazwyczaj ma znacznie większy wpływ na zrównoważony rozwój proje
Just one small typo 😄 
```suggestion
Możesz również spróbować przekonać swojego pracodawcę do sponsorowania Vue jako firma. Może to nie być łatwe, ale sponsoring biznesowy zazwyczaj ma znacznie większy wpływ na zrównoważony rozwój projektów Open Source Software (OSS) niż indywidualne darowizny, więc pomożesz nam znacznie bardziej, jeśli Ci się uda.
```

2024-07-08 07:31 UTC, szymonlicau approved these changes

2024-07-08 07:32 UTC, merged