[Docs > Tutorial] page translation
monterail/vue3-docs-pl pull request #77
Opened 2024-07-24 12:33 UTC by dkasperczyk

2024-07-26 12:12 UTC, szymonlicau requested changes

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-6/description.md
> +`<h1>` będzie renderowane tylko jeśli wartość `awesome` to [truthy].(https://developer.mozilla.org/en-US/docs/Glossary/Truthy). Jeśli `awesome` zmieni się na wartość [falsy](https://developer.mozilla
```suggestion
`<h1>` będzie renderowane tylko jeśli wartość `awesome` jest [truthy].(https://developer.mozilla.org/en-US/docs/Glossary/Truthy). Jeśli `awesome` zmieni się na wartość [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy), zostanie usunięty z drzewa DOM.
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-6/description.md
> +Więcej szczegółów na temat `v-if`: <a target="_blank" href="/guide/essentials/conditional.html">Przewonik - Renderowanie warunkowe</a>
```suggestion
Więcej szczegółów na temat `v-if`: <a target="_blank" href="/guide/essentials/conditional.html">Przewodnik - Renderowanie warunkowe</a>
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-7/description.md
> +Zauważ, że każdemu obiektowi todo nadajemy unikalne `id` i wiążemy go z <a target="_blank" href="/api/built-in-special-attributes.html#key">specjalnym atrybutem `key`</a> dla każdego `<li>`. Klucz `k
```suggestion
Zauważ, że każdemu obiektowi todo nadajemy unikalne `id` i wiążemy go ze <a target="_blank" href="/api/built-in-special-attributes.html#key">specjalnym atrybutem `key`</a> dla każdego `<li>`. Atrybut `key` pozwala Vue na dokładne przesunięcie każdego `<li>`, aby dopasować go do pozycji odpowiadającego mu obiektu w tablicy.
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-7/description.md
> +Więcej informacji na temat `v-for`: <a target="_blank" href="/guide/essentials/list.html">Przewonik - Renderowanie listy</a>
```suggestion
Więcej informacji na temat `v-for`: <a target="_blank" href="/guide/essentials/list.html">Przewodnik - Renderowanie listy</a>
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-8/description.md
> +Obliczana właściwość śledzi inne stany reaktywne używane w jej obliczeniach jako zależności. Buforuje wynik i automatycznie aktualizuje go, gdy zmieniają się jego zależności.
```suggestion
Właściwość computed śledzi inne stany reaktywne używane w jej obliczeniach jako zależności. Cache'uje wynik i automatycznie aktualizuje go, gdy zmieniają się jego zależności.
```
It might be better to stick to more familiar terms 😄

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-8/description.md
> +Teraz spróbuj dodać właściwość obliczaną `filteredTodos` i zaimplementuj jej logikę obliczeniową! Jeśli zostanie zaimplementowana poprawnie, zaznaczenie todo podczas ukrywania ukończonych elementów p
```suggestion
Teraz spróbuj dodać właściwość computed `filteredTodos` i zaimplementuj jej logikę obliczeniową! Jeśli zostanie zaimplementowana poprawnie, zaznaczenie todo podczas ukrywania ukończonych elementów powinno natychmiast je ukryć.
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-9/description.md
> +# Cykl życia i odnośniki do elementów w szablonie {#lifecycle-and-template-refs}
```suggestion
# Cykl życia i template refs {#lifecycle-and-template-refs}
```

2024-07-26 12:12 UTC, szymonlicau commented on src/tutorial/src/step-9/description.md
> +Aby uzyskać dostęp do referencji, musimy zadeklarować<span class="html"> i udostępnić</span> referencję o pasującej nazwie:
```suggestion
Aby uzyskać dostęp do referencji, musimy zadeklarować<span class="html"> i udostępnić</span> wartość ref o pasującej nazwie:
```

2024-07-31 09:26 UTC, dkasperczyk commented on src/tutorial/src/step-10/description.md
> +Tutaj używamy opcji `watch` do obserwowania zmian we właściwości `count`. Wywołanie zwrotne watch jest wywoływane, gdy zmienia się `count` i otrzymuje nową wartość jako argument. Więcej szczegółów zn
Personally, I would prefer to stick with English, but I checked how it was done in other translations, and they translated it as well. So maybe we should also translate technical words/sentences to Polish, even if they do not sound good. 🙈

2024-07-31 09:38 UTC, dkasperczyk commented on src/tutorial/src/step-8/description.md
> +Obliczana właściwość śledzi inne stany reaktywne używane w jej obliczeniach jako zależności. Buforuje wynik i automatycznie aktualizuje go, gdy zmieniają się jego zależności.
Agree!

2024-12-30 17:54 UTC, MateuszMichalowski requested changes
Some small suggestions added, on typo worth to fix.

2024-12-30 17:54 UTC, MateuszMichalowski commented on src/tutorial/src/step-1/description.md
> +Gotowy? Kliknij Następny, aby rozpocząć.
Shouldn't we keep quotation marks around "Następny"?

2024-12-30 17:54 UTC, MateuszMichalowski commented on src/tutorial/src/step-13/description.md
> +  // ddeklaracja zdarzeń emitujących
```suggestion
  // deklaracja zdarzeń emitujących
```

2024-12-30 17:54 UTC, MateuszMichalowski commented on src/tutorial/src/step-13/description.md
> +    // emitowanie zdarzenie z argumentem
```suggestion
    // emitowanie z argumentem
```
WDYT?

2024-12-30 17:54 UTC, MateuszMichalowski commented on src/tutorial/src/step-13/description.md
> +    // emitowanie zdarzenie z argumentem
```suggestion
    // emitowanie z argumentem
```
WDYT?

2025-01-30 10:47 UTC, Baroshem commented on src/tutorial/src/step-1/description.md
> +Gotowy? Kliknij Następny, aby rozpocząć.
Fixed in the last commit :)

2025-01-30 10:47 UTC, merged