Non context text translation
monterail/vue3-docs-pl pull request #78
Opened 2024-07-26 11:48 UTC by dkasperczyk

2024-11-22 08:27 UTC, Baroshem requested changes
Few small changes

2024-12-30 13:07 UTC, MateuszMichalowski commented on .vitepress/config.ts
> +    text: 'Plac zabaw',
It might be only me but I'm not sure if this one should be translated.

2024-12-30 13:09 UTC, MateuszMichalowski commented on .vitepress/config.ts
> +      { text: 'Nowe wydania', link: '/about/releases' },
Shouldn't it be only "Wydania"?

2024-12-30 17:28 UTC, MateuszMichalowski requested changes
Some small suggestions from me.

2025-01-30 10:49 UTC, Baroshem commented on .vitepress/config.ts
> +    text: 'Plac zabaw',
I have changed it to `Interaktywne demo`

2025-01-30 10:49 UTC, Baroshem commented on .vitepress/config.ts
> +      { text: 'Nowe wydania', link: '/about/releases' },
Fixed

2025-01-30 10:50 UTC, Baroshem commented on .vitepress/config.ts
> +          text: 'Cykle życia',
Fixed

2025-01-30 10:50 UTC, Baroshem commented on .vitepress/config.ts
> +        { text: 'Rekwizyty', link: '/guide/components/props' },
I left it as `Props`

2025-01-30 10:50 UTC, Baroshem commented on .vitepress/config.ts
> +          text: 'Atrybuty Przepadające',
I left it as `Atrybuty Fallthrough`

2025-01-30 10:50 UTC, Baroshem commented on .vitepress/config.ts
> +        { text: 'Pluginy', link: '/guide/reusability/plugins' }
Fixed

2025-01-30 10:50 UTC, Baroshem commented on .vitepress/config.ts
> +      text: 'Skalowalnie w góre',
Fixed

2025-01-30 10:51 UTC, Baroshem commented on .vitepress/config.ts
> +          text: 'Haki cyklu życia',
Fixed

2025-01-30 10:51 UTC, Baroshem approved these changes

2025-01-30 10:52 UTC, merged