feat: translate best practices page
monterail/vue3-docs-pl pull request #85
Opened 2024-12-05 12:41 UTC by Baroshem

## Description of Problem

## Proposed Solution

## Additional Information

2024-12-10 13:44 UTC, szymonlicau requested changes
Very comprehensive work - good job! 👍 

I left some corrections and small suggestions over some wording styles or to maybe keep some definitions in english.

Let me know what you think 😄

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/security.md
> +Załóżmy, że `sanitizedUrl` został wyczyszczony, tak aby był to z pewnością prawdziwy adres URL, a nie JavaScript. Dzięki `userProvidedStyles` złośliwi użytkownicy mogliby nadal udostępniać CSS, aby „
```suggestion
Załóżmy, że `sanitizedUrl` został wyczyszczony, tak aby był to z pewnością prawdziwy adres URL, a nie JavaScript. Dzięki `userProvidedStyles` złośliwi użytkownicy mogliby nadal udostępniać CSS, aby „przechwytywać kliknięcia”, np. stylizując łącze w przezroczyste pole nad przyciskiem „Zaloguj się”. Następnie, jeśli `https://user-controlled-website.com/` jest zbudowany tak, aby przypominał stronę logowania Twojej aplikacji, mogliby po prostu przechwycić prawdziwe dane logowania użytkownika.
```

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/security.md
> +## Koordynacja zaplecza {#backend-coordination}
```suggestion
## Koordynacja z backendem {#backend-coordination}
```

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/security.md
> +Luki w zabezpieczeniach HTTP, takie jak fałszowanie żądań między witrynami (CSRF/XSRF) i dołączanie skryptów między witrynami (XSSI), są rozwiązywane głównie w zapleczu, więc nie są problemem Vue. Ni
```suggestion
Luki w zabezpieczeniach HTTP, takie jak fałszowanie żądań między witrynami (CSRF/XSRF) i dołączanie skryptów między witrynami (XSSI), są rozwiązywane głównie w backendzie, więc nie są problemem Vue. Niemniej jednak nadal dobrym pomysłem jest komunikacja z zespołem backendowym, aby dowiedzieć się, jak najlepiej współdziałać z ich API, np. przesyłając tokeny CSRF wraz z formularzami.
```

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/production-deployment.md
> +Podczas rozwoju Vue zapewnia szereg funkcji, które poprawiają doświadczenie programistyczne:
```suggestion
Podczas pracy Vue zapewnia szereg funkcji, które poprawiają doświadczenie programistyczne:
```

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/production-deployment.md
> +- Walidacja rekwizytów/zdarzeń
```suggestion
- Walidacja props i emitowanych zdarzeń
```

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/accessibility.md
> +## Pomiń link {#skip-link}
```suggestion
## Skip link {#skip-link}
```
I saw it used consistently this way even in Polish discussions 🤔

2024-12-10 13:44 UTC, szymonlicau commented on src/guide/best-practices/accessibility.md
> +Gdy użytkownik zmieni trasę, przywróć fokus do linku pomijającego. Można to osiągnąć, wywołując fokus na szablonie ref linku pomijającego (zakładając użycie `vue-router`):
```suggestion
Gdy użytkownik zmieni adres, przywróć fokus do linku pomijającego. Można to osiągnąć, wywołując focus na szablonie ref linku pomijającego (zakładając użycie `vue-router`):
```

2024-12-10 15:08 UTC, Baroshem commented on src/guide/best-practices/performance.md
> +### Wielkość pakietu i potrząsanie drzewami {#bundle-size-and-tree-shaking}
```suggestion
### Bundle size i tree-shaking {#bundle-size-and-tree-shaking}
```

2024-12-10 15:08 UTC, Baroshem commented on src/guide/best-practices/performance.md
> +### Podział kodu {#code-splitting}
```suggestion
### Code splitting {#code-splitting}
```

2024-12-11 08:33 UTC, szymonlicau approved these changes
:shipit:

2024-12-11 10:18 UTC, merged